#index:
#    path: /
#    controller: App\Controller\DefaultController::index

accueil:
    path: /accueil
    controller: App\Controller\EtudiantController::index
    
#Compétence
competenceAjouter:
    path: /competence/ajouter
    controller: App\Controller\CompetenceController::ajouterCompetence
    
competenceConsulter:    
    path: /competence/{id}
    controller: App\Controller\CompetenceController::consulterCompetence
    
competenceLister:
    path: /competence/
    controller: App\Controller\CompetenceController::listerCompetence
    
#Étudiants
etudiantAjouter:
    path: /etudiant/ajouter
    controller: App\Controller\EtudiantController::ajouterEtudiant
    
etudiantConsulter:    
    path: /etudiant/{id}
    controller: App\Controller\EtudiantController::consulterEtudiant
        
etudiantLister:
    path: /etudiant/
    controller: App\Controller\EtudiantController::listerEtudiant
    
etudiantModifier:
    path: /etudiant/{id}/modifier
    controller: App\Controller\EtudiantController::modifierEtudiant
    
#Maison
maisonAjouter:
    path: /maison/ajouter
    controller: App\Controller\MaisonController::ajouterMaison
    
maisonConsulter:    
    path: /maison/{id}
    controller: App\Controller\MaisonController::consulterMaison
    
maisonLister:
    path: /maison/
    controller: App\Controller\MaisonController::listerMaison
    
